title: Dhruv Sumathi
email: dhruv.sumathi@gmail.com
description: "work in progress"
baseurl: "" # leave empty if deploying at the domain root
url: "https://dhruvsumathi.xyz" # replace with your domain
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /projects/:path/
  travel:
    output: true
    permalink: /travel/:path/

# Only these pages will appear in the top navigation
header_pages:
  - about.md
  - projects.md
  - writing.md
  - film-photo.md
  - travel.md
